---
title: "Unfolding_curves"
author: "Antdrew D. Nguyen"
date: "2016-April-26"
output: pdf_document
---

#Loading libraries and functions
```{r}
library(ggplot2)
library(tidyr)
library(minpack.lm)

nls.fit<-function(data=data){
  y<-nlsLM(unfolding ~ min+ (1-min)/(1+exp((-slope*(Tm-T)))),data=data, 
           start=list(slope=.5,Tm=45,min=.3),
           trace=TRUE,control=nls.control(warnOnly = TRUE, tol = 1e-05, maxiter=1000))
  #return(y)
  return(summary(y)$coefficients)
  }


#Function that predicts values given parameter estimates of curves
fud<-function(T=seq(25,50,1),Tm=40,slope=.5,max=1,min=0){
  y<-min+ (max-min)/(1+exp((-slope*(Tm-T))))
  return(y)
  }

```

#20160520
```{r total protein}
x<-read.csv("../Data/20160520_total_protein_unfolding.csv")
x.par<-subset(x,x$TN=="N" & x$Species!="A. picea")

str(x.par)

x.par

mod1<-ddply(x.par,.(Species,Colony),nls.fit)
mod1$parameter<-rep(c("slope","Tm","min"),length(mod1$Species)/3)
knitr::kable(mod1)

Tm<-subset(mod1,mod1$parameter=="Tm")
Tm
summary(aov(Estimate~Species,data=Tm))

slope<-subset(mod1,mod1$parameter=="slope")
slope
summary(aov(Estimate~Species,data=slope))
boxplot(Estimate~Species,data=slope,las=1,ylab="slope parameter")


min<-subset(mod1,mod1$parameter=="min")
min
summary(aov(Estimate~Species,data=min))

ggplot(x.par,aes())
```


#Comparing aphaeno and pogo
```{r comparing pogo and aphaeno}
#pogo
T<-c(25,30,35,40,43,45,48,50,55,60,65,70)
ten<-c(1.00,0.984,0.974,0.795,0.787,0.726,0.640,0.574,0.482,0.379,0.387,0.392)
ten.dat<-as.data.frame(cbind(T,ten));names(ten.dat)[2]<-"unfolding"
unfold_10min<-nls.fit(ten.dat)
#Aphaeno
avon<-c(0.963,1.00,0.940,0.882,0.755,0.627,0.600,0.549,0.502,0.444,0.368,0.379)
aph<-as.data.frame(cbind(T,avon));names(aph)[2]<-"unfolding"
aph.fit<-nls.fit(aph)
#Table of fitted curves
knitr::kable(round(cbind(unfold_10min,aph.fit),3))
#difference in TMs
46.16-44.754


#lets plot these out with all parameters
plot(seq(25,70,.1),fud(T=seq(25,70,.1),max=1,min=0.3958177,Tm=44.7544257,slope=0.2156598),pch=16,col="blue",ylab="Proportion non-denatured",xlab="Temperature",ylim=c(.3,1))
points(seq(25,70,.1),fud(T=seq(25,70,.1),max=1,min=0.3704093,Tm=46.159662,slope=0.1923073),pch=16,col="red")
points(ten.dat$T,ten.dat$unfolding,pch=16,col="red",cex=2)
points(aph$T,aph$unfolding,pch=16,col="blue",cex=2)
legend(55,1,c("Pogonomyrmex barbatus","Aphaenogaster picea"),text.font=3,pch=16,col=c("red","blue"))
#abline(v=c(46.1596629,44.7544257),lty=c(1,3),lwd=3)

##plot by only slope
plot(seq(25,70,.1),fud(T=seq(25,70,.1),slope= 0.192,Tm=45),pch=16,col="blue",ylab="Proportion non-denatured",xlab="Temperature")
points(seq(25,70,.1),fud(T=seq(25,70,.1),slope= 0.216,Tm=45),pch=16,col="red")
legend(55,1,c("Pogonomyrmex barbatus","Aphaenogaster picea"),text.font=3,pch=16,col=c("red","blue"))
```


#comparing 10 vs 20 min
```{r comparing the 10 min vs 20 min at each temp}
# 10 min inc
#earlier
unfold_10min<-nls.fit(ten.dat)
# 20 min incubation
twen<-c(0.977,0.988,1.00,0.822,0.664,0.564,0.479,0.473,0.432,0.350,0.315,0.304)
ty.dat<-as.data.frame(cbind(T,twen));names(ty.dat)[2]<-"unfolding"
unfold_20min<-nls.fit(ty.dat);unfold_20min

knitr::kable(round(cbind(unfold_10min,unfold_20min),3))

#plots


plot(seq(25,70,.1),fud(T=seq(25,70,.1),max=1,min=0.3452337,Tm=43.2788185,slope=0.2824321),pch=16,col="red",ylab="Proportion non-denatured",xlab="Temperature",ylim=c(.3,1))
points(seq(25,70,.1),fud(T=seq(25,70,.1),max=1,min=0.3704093,Tm=46.159662,slope=0.1923073),pch=16,col="black")
points(ten.dat$T,ten.dat$unfolding,pch=16,col="black",cex=2)
points(ty.dat$T,ty.dat$unfolding,pch=16,col="red",cex=2)
abline(v=c(46.1596629,43.2788185),lty=c(1,3),lwd=3)
legend(55,1,c("10 minute","20 minute"),pch=16,col=c("black","red"))

```

#How to sample a reaction norm?

```{r rxn norm}

unfolding<-fud(T=seq(25,70,1),Tm=45,slope=.2,min=.4)
T<-seq(25,70,1)
com<-cbind(T,unfolding);head(com)
plot(T,unfolding,ylab="Poportion non-denatured",xlab="Temperature (C)",las=1)

#sample random points
n<-as.data.frame(com[sample(nrow(com), 10), ])# randomly sampling
n<-n[order(n$T),]
n$unfolding<-n[,2]+rnorm(mean=0,sd=0.02,n=10)# adding error

plot(n$T,n$unfolding,pch=16,col="black",cex=2,ylim=c(.4,1))
lines(T,unfolding)
tt<-nls.fit(n)
tt
lines(seq(25,70,.1),fud(Tm=tt[2],slope=tt[1],min=tt[3],T=seq(25,70,.1)),col="red",lwd=2)
legend(45,1,c("Known curve","Modeled based on points"),pch="-",col=c("black","red"),cex=1.5)
knitr::kable(tt)
#mean(nndist(n$T))

#try nearest neighbor
#http://www.statsoft.com/textbook/k-nearest-neighbors
library(spatstat)




```

