---
title: "Analysis of whole ant protein lysates"
author: "Andrew Nguyen"
date: "2016-January-21"
output: pdf_document
---
#Rationale
#Objectives
```{r libraries}
library(plyr)
library(ggplot2)
```

```{r load data}
x<-read.csv("20160121_prot_native_aph_pog_buffer.csv")
str(x)
```

#Differences among isolation methods and species
```{r}
mod1<-aov(total~Temperature*Species+Temperature*Buffer,data=x)
summary(mod1)


```

#Figure
```{r figure}
T<-theme_bw()+theme(text=element_text(size=30),axis.text=element_text(size=30),panel.grid.major=element_blank(),panel.grid.minor.x = element_blank(),panel.grid = element_blank(),legend.key = element_blank())
#ggplot(data=x,aes(x=Buffer,y=total))+geom_boxplot()

parsed<-ddply(x,.(Temperature,Species,Buffer),summarize,total=mean(na.exclude(total)),prop=mean(na.exclude(prop)))

ggplot(parsed,aes(x=Temperature,y=prop,color=factor(Species),shape=factor(Buffer)))+geom_point(size=6)+geom_line()+T+scale_y_continuous("Proportion of proteins non-denatured",limits=c(.3,1),breaks=seq(.1,1,.1))+scale_x_continuous("Temperature",limits=c(20,80),breaks=seq(20,80,10))

#write.csv(parsed,"test.csv")
#fitting curve 
#y = a/(1+bc^-x)
#a=1
#c=.1
#1/(1+b*(.1^-Temperature))
test<-read.csv("test.csv")
nls(prop~1/(1+exp(-b*Temperature)),data=test[1:8,],start=list(b=-10),trace=TRUE,control=nls.control(warnOnly = TRUE, tol = 1e-05, maxiter=1000))

gl.mod<-glm(prop~Temperature,family=Gamma,data=test[1:8,])
summary(gl.mod)


Temperature<-data.frame(seq(25,80,1));names(Temperature)<-"Temperature"
val<-predict(gl.mod,type="response",newdata=Temperature)

plot(test[1:8,2],test[1:8,6])
lines(Temperature[,1],val)
```

#20160209_trials
##pogo and buffer comparison
###spun at 100,000g 20 min this time
```{r}
m<-read.csv("20160209_parsed_anbe_prot_unfolding_pogo.csv")
str(m)

pog<-subset(m,m$Sample=="pogo")
pog.response<-colMeans(pog[,-1])
pog.response<-pog.response-min(pog.response)
plot(seq(4,90,1),pog.response,xlim=c(20,60))
plot(seq(4,90,1),pog.response)
pog_20_60<-pog.response[20:60]-min(pog.response)

plot(seq(20,60,1),pog_20_60)
pog_prop<-pog_20_60/max(pog_20_60)
plot(seq(20,60,1),pog_prop)
dat<-as.data.frame(cbind(pog_prop,seq(20,60,1)))
#boltzmann function fit
B<-nls(pog_prop~(min+(1-min)/(1+exp((inflect-V2)/a))),data=dat,start=list(min=min(pog_prop),inflect=45,a=1.05), trace=TRUE,control=nls.control(warnOnly = TRUE, tol = 1e-05, maxiter=1000))

summary(B)

plot(seq(20,60,1),pog_prop,ylim=c(0,1))
lines(dat$V2,predict(B,list(temp=dat$V2)),lwd=3)
abline(v=44.576,lwd=2)
```
#20160209_test 10 colony prot
```{r}
t<-read.csv("20160209_prot_stability_10colonies.csv")
tech.means<-ddply(t,.(Sample),function(x){colMeans(x[,-1:-2])})
temp<-seq(4,90,1)

#getting min values per sample
new<-as.data.frame(t(apply(tech.means[,-1],1,function(x){(x-min(x))/max(x-min(x))})))
tech.means$Sample
plot(temp,new[1,],ylim=c(0,1),col="blue",pch=16,xlim=c(20,70))#ala1
points(temp,new[7,],col="blue",pch=16)#kite3
points(temp,new[8,],col="blue",pch=16)#lex9

points(temp,new[4,],col="orange",pch=17)#fb2
points(temp,new[5,],col="orange",pch=17)#fb5
points(temp,new[6,],col="orange",pch=17)#kh3

#plot(temp,new[2,],ylim=c(0,1))#control
points(temp,new[3,],col="green",pch=18)#exit69
points(temp,new[11,],col="green",pch=18)#sal13

points(temp,new[9,],col="red",pch=20)#17-10
points(temp,new[10,],col="red",pch=20)#17-10

newer<-as.data.frame(cbind(tech.means$Sample,new[,24:73]))
names(newer)[1]<-"Sample"

library(tidyr)
long.new<-gather(newer,Temp,prop,X24:X73)
long.new<-long.new[order(long.new$Sample),]

long.new$temp<-rep(seq(20,69,1),11)

long.new


ddply(long.new,.(Sample),function(x){summary(nls(prop~(min+(1-min)/(1+exp((inflect-temp)/a))),data=x,start=list(min=min(prop),inflect=45,a=1.05), trace=TRUE,control=nls.control(warnOnly = TRUE, tol = 1e-05, maxiter=1000)))})

#
ala1<-long.new[1:50,]
B<-nls(prop~(min+(1-min)/(1+exp((inflect-temp)/a))),data=ala1,start=list(min=min(prop),inflect=45,a=1.05), trace=TRUE,control=nls.control(warnOnly = TRUE, tol = 1e-05, maxiter=1000))
```

